language: rust

addons:
  firefox: latest

before_install:
  - export GECKO_VERSION=0.24.0
  - wget https://github.com/mozilla/geckodriver/releases/download/v$GECKO_VERSION/geckodriver-v$GECKO_VERSION-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v$GECKO_VERSION-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install v10.15.3
  - npm install -g yarn
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

script:
  - yarn install
  - yarn test
