[package]
name = "mywasmrs-root"
version = "0.1.0"
authors = ["gky360 <gky360@gmail.com>"]
edition = "2018"


[workspace]
members = [ "crate" ]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"